In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df  = pd.read_csv(r"C:\Users\HP\Desktop\ML projects\T_20 cricket Prediction\ball_by_ball_it20.csv")

In [5]:
df.head()

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,0,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,1,BA King,...,South Africa,1,1,0,1,0,NaN,NaN,1,1
1,1,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,2,KR Mayers,...,South Africa,1,1,1,1,1,NaN,NaN,1,1
2,2,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,3,BA King,...,South Africa,1,0,1,0,1,1.0,2.0,0,1
3,3,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,4,J Charles,...,South Africa,1,0,1,1,1,NaN,NaN,0,1
4,4,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,5,J Charles,...,South Africa,1,4,1,2,1,NaN,NaN,4,1

In [54]:
df.isnull().sum()

Unnamed: 0                      0
Match ID                        0
Date                            0
Venue                           0
Bat First                       0
Bat Second                      0
Innings                         0
Over                            0
Ball                            0
Batter                          0
Non Striker                     0
Bowler                          0
Batter Runs                     0
Extra Runs                      0
Runs From Ball                  0
Ball Rebowled                   0
Extra Type                      0
Wicket                          0
Method                     401460
Player Out                 401460
Innings Runs                    0
Innings Wickets                 0
Target Score                    0
Runs to Get                224815
Balls Remaining                 0
Winner                          0
Chased Successfully             0
Total Batter Runs               0
Total Non Striker Runs          0
Batter Balls Faced              0
Non Striker Balls Faced         0
Player Out Runs            401460
Player Out Balls Faced     401460
Bowler Runs Conceded            0
Valid Ball                      0
dtype: int64

In [16]:

df.columns

Index(['Unnamed: 0', 'Match ID', 'Date', 'Venue', 'Bat First', 'Bat Second',
       'Innings', 'Over', 'Ball', 'Batter', 'Non Striker', 'Bowler',
       'Batter Runs', 'Extra Runs', 'Runs From Ball', 'Ball Rebowled',
       'Extra Type', 'Wicket', 'Method', 'Player Out', 'Innings Runs',
       'Innings Wickets', 'Target Score', 'Runs to Get', 'Balls Remaining',
       'Winner', 'Chased Successfully', 'Total Batter Runs',
       'Total Non Striker Runs', 'Batter Balls Faced',
       'Non Striker Balls Faced', 'Player Out Runs', 'Player Out Balls Faced',
       'Bowler Runs Conceded', 'Valid Ball'],
      dtype='object')

In [18]:
df.head(1)

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,0,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,1,BA King,...,South Africa,1,1,0,1,0,NaN,NaN,1,1

In [19]:
data = {
    f'col{i}': range(10) for i in range(1, 36)
}

# Splitting the DataFrame into three smaller DataFrames
df1 = df.iloc[:, :12]
df2 = df.iloc[:, 12:24]
df3 = df.iloc[:, 24:35]

In [216]:
df1.head(8)

,Unnamed: 0,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,Bowler
0,0,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,1,BA King,KR Mayers,WD Parnell
1,1,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,2,KR Mayers,BA King,WD Parnell
2,2,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,3,BA King,KR Mayers,WD Parnell
3,3,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,4,J Charles,KR Mayers,WD Parnell
4,4,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,5,J Charles,KR Mayers,WD Parnell
5,5,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,1,6,J Charles,KR Mayers,WD Parnell
6,6,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,2,1,KR Mayers,J Charles,AK Markram
7,7,1339605,2023-03-26,SuperSport Park,West Indies,South Africa,1,2,2,KR Mayers,J Charles,AK Markram

In [26]:
df2.head()

,Batter Runs,Extra Runs,Runs From Ball,Ball Rebowled,Extra Type,Wicket,Method,Player Out,Innings Runs,Innings Wickets,Target Score,Runs to Get
0,1,0,1,0,[],0,NaN,NaN,1,0,259,NaN
1,1,0,1,0,[],0,NaN,NaN,2,0,259,NaN
2,0,0,0,0,[],1,caught,BA King,2,1,259,NaN
3,0,0,0,0,[],0,NaN,NaN,2,1,259,NaN
4,4,0,4,0,[],0,NaN,NaN,6,1,259,NaN

In [40]:
#df3['Chased Successfully'].value_counts()
df3.head(1)

,Balls Remaining,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,119,South Africa,1,1,0,1,0,NaN,NaN,1,1

In [296]:
matches = df[['Match ID','Venue','Winner','Bat First','Bat Second','Target Score']]

In [35]:
#matches.head()

In [231]:
deliveries = df[['Match ID','Venue','Innings','Bat First','Bat Second','Batter','Winner','Non Striker','Bowler','Ball','Batter Runs','Extra Runs','Runs From Ball','Ball Rebowled','Extra Type','Wicket','Method','Player Out','Innings Runs','Innings Wickets','Target Score','Runs to Get'
	,'Balls Remaining']]

In [343]:
deliveries.head(785)

,Match ID,Venue,Innings,Bowling Side,Batting Side,Batter,Winner,Non Striker,Bowler,Ball,...,Method,Player Out,Current Score,Target Score,Required Runs,Balls Remaining,Wickets Left,RR,CR,Result
194,1339605,SuperSport Park,2,West Indies,South Africa,Q de Kock,South Africa,RR Hendricks,RA Reifer,5,...,caught,Q de Kock,152,259,107.0,55,9,11.672727,14.030769,1
202,1339605,SuperSport Park,2,West Indies,South Africa,RR Rossouw,South Africa,RR Hendricks,OF Smith,6,...,caught,RR Rossouw,180,259,79.0,48,8,9.875000,15.000000,1
207,1339605,SuperSport Park,2,West Indies,South Africa,RR Hendricks,South Africa,DA Miller,R Powell,4,...,caught,RR Hendricks,193,259,66.0,44,7,9.000000,15.236842,1
226,1339605,SuperSport Park,2,West Indies,South Africa,DA Miller,South Africa,AK Markram,JO Holder,4,...,caught,DA Miller,216,259,43.0,26,6,9.923077,13.787234,1
1331,356009,Lord's,2,Sri Lanka,Ireland,WTS Porterfield,Sri Lanka,NJ O'Brien,M Muralitharan,1,...,caught,WTS Porterfield,59,145,86.0,65,9,7.938462,6.436364,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53333,682917,Sylhet Stadium,2,United Arab Emirates,Zimbabwe,BRM Taylor,Zimbabwe,Sikandar Raza,EHSN Silva,4,...,caught,BRM Taylor,22,117,95.0,104,8,5.480769,8.250000,1
53338,682917,Sylhet Stadium,2,United Arab Emirates,Zimbabwe,SC Williams,Zimbabwe,Sikandar Raza,AM Guruge,3,...,caught and bowled,SC Williams,24,117,93.0,99,7,5.636364,6.857143,1
53358,682917,Sylhet Stadium,2,United Arab Emirates,Zimbabwe,Sikandar Raza,Zimbabwe,V Sibanda,Ahmed Raza,5,...,caught,Sikandar Raza,34,117,83.0,79,6,6.303797,4.975610,1
53372,682917,Sylhet Stadium,2,United Arab Emirates,Zimbabwe,V Sibanda,Zimbabwe,E Chigumbura,Khurram Khan,1,...,caught and bowled,V Sibanda,63,117,54.0,65,5,4.984615,6.872727,1
53768,1298176,Melbourne Cricket Ground,2,India,Zimbabwe,W Madhevere,India,CR Ervine,B Kumar,1,...,caught,W Madhevere,0,187,187.0,119,9,9.428571,0.000000,0

In [233]:
matches['Bat First'].unique()

array(['West Indies', 'Sri Lanka', 'England', 'United Arab Emirates',
       'Bangladesh', 'India', 'Papua New Guinea', 'Afghanistan',
       'Netherlands', 'Ireland', 'New Zealand', 'Pakistan', 'Nepal',
       'Scotland', 'South Africa', 'Australia', 'Oman', 'Zimbabwe',
       'Hong Kong', 'Canada', 'Namibia', 'Kenya', 'Austria',
       'United States of America', 'Denmark'], dtype=object)

In [272]:
Teams = ['West Indies', 'Scotland',
       'Sri Lanka', 'England',
       'United Arab Emirates', 'Denmark', 'Bangladesh',
       'India', 'Papua New Guinea', 'Afghanistan', 
       'Netherlands', 'Ireland', 'New Zealand','Pakistan',
      'Nepal', 'South Africa', 'Australia',
       'Oman','Zimbabwe', 'Hong Kong', 'Kenya', 'Canada','Namibia',
       'United States of America', 
      ]

In [273]:
len(Teams)

24

In [279]:
matches = matches[matches['Bat First'].isin(Teams)]
matches = matches[matches['Bat Second'].isin(Teams)]

In [297]:
deliveries = deliveries[deliveries['Bat Second'].isin(Teams)]
deliveries = deliveries[deliveries['Bat First'].isin(Teams)]

KeyError: 'Bat Second'

In [298]:
deliveries = deliveries[deliveries['Innings'] == 2]

In [299]:
deliveries.shape

(7092, 25)

In [283]:
deliveries = deliveries.rename(columns = {'Innings Runs': 'Current Score','Innings Wickets':'Wickets','Runs to Get':'Required Runs','Runs From Ball':'Run scored'})

In [284]:
deliveries.head()

,Match ID,Venue,Innings,Bowling Side,Batting Side,Batter,Winner,Non Striker,Bowler,Ball,...,Player Out,Current Score,Wickets,Target Score,Required Runs,Balls Remaining,Wickets Left,RR,CR,Result
194,1339605,SuperSport Park,2,West Indies,South Africa,Q de Kock,South Africa,RR Hendricks,RA Reifer,5,...,Q de Kock,152,1,259,107.0,55,9,11.672727,14.030769,1
202,1339605,SuperSport Park,2,West Indies,South Africa,RR Rossouw,South Africa,RR Hendricks,OF Smith,6,...,RR Rossouw,180,2,259,79.0,48,9,9.875000,15.000000,1
207,1339605,SuperSport Park,2,West Indies,South Africa,RR Hendricks,South Africa,DA Miller,R Powell,4,...,RR Hendricks,193,3,259,66.0,44,9,9.000000,15.236842,1
226,1339605,SuperSport Park,2,West Indies,South Africa,DA Miller,South Africa,AK Markram,JO Holder,4,...,DA Miller,216,4,259,43.0,26,9,9.923077,13.787234,1
1331,356009,Lord's,2,Sri Lanka,Ireland,WTS Porterfield,Sri Lanka,NJ O'Brien,M Muralitharan,1,...,WTS Porterfield,59,1,145,86.0,65,9,7.938462,6.436364,0

In [285]:
#deliveries = deliveries.drop(columns = {"Method","Player Out"})

In [300]:
deliveries.head()

,Match ID,Venue,Innings,Bowling Side,Batting Side,Batter,Winner,Non Striker,Bowler,Ball,...,Method,Player Out,Current Score,Target Score,Required Runs,Balls Remaining,Wickets Left,RR,CR,Result
194,1339605,SuperSport Park,2,West Indies,South Africa,Q de Kock,South Africa,RR Hendricks,RA Reifer,5,...,caught,Q de Kock,152,259,107.0,55,9,11.672727,14.030769,1
202,1339605,SuperSport Park,2,West Indies,South Africa,RR Rossouw,South Africa,RR Hendricks,OF Smith,6,...,caught,RR Rossouw,180,259,79.0,48,8,9.875000,15.000000,1
207,1339605,SuperSport Park,2,West Indies,South Africa,RR Hendricks,South Africa,DA Miller,R Powell,4,...,caught,RR Hendricks,193,259,66.0,44,7,9.000000,15.236842,1
226,1339605,SuperSport Park,2,West Indies,South Africa,DA Miller,South Africa,AK Markram,JO Holder,4,...,caught,DA Miller,216,259,43.0,26,6,9.923077,13.787234,1
1331,356009,Lord's,2,Sri Lanka,Ireland,WTS Porterfield,Sri Lanka,NJ O'Brien,M Muralitharan,1,...,caught,WTS Porterfield,59,145,86.0,65,9,7.938462,6.436364,0

In [303]:
#deliveries["Wickets Left"] = 10 - deliveries['Wickets']

In [304]:
#deliveries = deliveries.drop(columns = {"Wickets"})

In [305]:
deliveries.head()

,Match ID,Venue,Innings,Bowling Side,Batting Side,Batter,Winner,Non Striker,Bowler,Ball,...,Method,Player Out,Current Score,Target Score,Required Runs,Balls Remaining,Wickets Left,RR,CR,Result
194,1339605,SuperSport Park,2,West Indies,South Africa,Q de Kock,South Africa,RR Hendricks,RA Reifer,5,...,caught,Q de Kock,152,259,107.0,55,9,11.672727,14.030769,1
202,1339605,SuperSport Park,2,West Indies,South Africa,RR Rossouw,South Africa,RR Hendricks,OF Smith,6,...,caught,RR Rossouw,180,259,79.0,48,8,9.875000,15.000000,1
207,1339605,SuperSport Park,2,West Indies,South Africa,RR Hendricks,South Africa,DA Miller,R Powell,4,...,caught,RR Hendricks,193,259,66.0,44,7,9.000000,15.236842,1
226,1339605,SuperSport Park,2,West Indies,South Africa,DA Miller,South Africa,AK Markram,JO Holder,4,...,caught,DA Miller,216,259,43.0,26,6,9.923077,13.787234,1
1331,356009,Lord's,2,Sri Lanka,Ireland,WTS Porterfield,Sri Lanka,NJ O'Brien,M Muralitharan,1,...,caught,WTS Porterfield,59,145,86.0,65,9,7.938462,6.436364,0

In [306]:
deliveries['RR'] = (deliveries['Required Runs']/deliveries['Balls Remaining'])*6
deliveries['CR'] = (deliveries['Current Score']/(120 - deliveries['Balls Remaining'])*6)

In [307]:
deliveries.head(6)

,Match ID,Venue,Innings,Bowling Side,Batting Side,Batter,Winner,Non Striker,Bowler,Ball,...,Method,Player Out,Current Score,Target Score,Required Runs,Balls Remaining,Wickets Left,RR,CR,Result
194,1339605,SuperSport Park,2,West Indies,South Africa,Q de Kock,South Africa,RR Hendricks,RA Reifer,5,...,caught,Q de Kock,152,259,107.0,55,9,11.672727,14.030769,1
202,1339605,SuperSport Park,2,West Indies,South Africa,RR Rossouw,South Africa,RR Hendricks,OF Smith,6,...,caught,RR Rossouw,180,259,79.0,48,8,9.875000,15.000000,1
207,1339605,SuperSport Park,2,West Indies,South Africa,RR Hendricks,South Africa,DA Miller,R Powell,4,...,caught,RR Hendricks,193,259,66.0,44,7,9.000000,15.236842,1
226,1339605,SuperSport Park,2,West Indies,South Africa,DA Miller,South Africa,AK Markram,JO Holder,4,...,caught,DA Miller,216,259,43.0,26,6,9.923077,13.787234,1
1331,356009,Lord's,2,Sri Lanka,Ireland,WTS Porterfield,Sri Lanka,NJ O'Brien,M Muralitharan,1,...,caught,WTS Porterfield,59,145,86.0,65,9,7.938462,6.436364,0
1359,356009,Lord's,2,Sri Lanka,Ireland,AR White,Sri Lanka,NJ O'Brien,KMDN Kulasekara,5,...,caught,AR White,87,145,58.0,37,8,9.405405,6.289157,0

In [308]:
# for team in deliveries['Bat Second']:
#     if team == deliveries['Winner']:
#         deliveries['Result'] = 1
#     else :
#         deliveries['Result'] =0

In [310]:
deliveries['Result'] = np.where(deliveries['Batting Side'] == deliveries['Winner'], 1, 0)

In [311]:
deliveries.head(1)

,Match ID,Venue,Innings,Bowling Side,Batting Side,Batter,Winner,Non Striker,Bowler,Ball,...,Method,Player Out,Current Score,Target Score,Required Runs,Balls Remaining,Wickets Left,RR,CR,Result
194,1339605,SuperSport Park,2,West Indies,South Africa,Q de Kock,South Africa,RR Hendricks,RA Reifer,5,...,caught,Q de Kock,152,259,107.0,55,9,11.672727,14.030769,1

In [312]:
deliveries.dropna(inplace=True)

In [313]:
deliveries = deliveries[deliveries['Balls Remaining'] != 0]

In [314]:
deliveries.shape

(7092, 25)

In [315]:
deliveries = deliveries.rename(columns = {'Bat First':'Bowling Side','Bat Second': 'Batting Side'})

In [316]:
#deliveries.head()

In [317]:
Final_doc = deliveries[['Bowling Side','Batting Side','Venue','Target Score','Required Runs','Balls Remaining','CR','RR','Wickets Left','Result']]

In [342]:
Final_doc.dropna(inplace=True)
Final_doc = Final_doc[Final_doc['Balls Remaining'] != 0]
Final_doc = Final_doc[Final_doc['Wickets Left'] != 0]
Final_doc.head(35)

,Bowling Side,Batting Side,Venue,Target Score,Required Runs,Balls Remaining,CR,RR,Wickets Left,Result
194,West Indies,South Africa,SuperSport Park,259,107.0,55,14.030769,11.672727,9,1
202,West Indies,South Africa,SuperSport Park,259,79.0,48,15.000000,9.875000,8,1
207,West Indies,South Africa,SuperSport Park,259,66.0,44,15.236842,9.000000,7,1
226,West Indies,South Africa,SuperSport Park,259,43.0,26,13.787234,9.923077,6,1
1331,Sri Lanka,Ireland,Lord's,145,86.0,65,6.436364,7.938462,9,0
1359,Sri Lanka,Ireland,Lord's,145,58.0,37,6.289157,9.405405,8,0
1363,Sri Lanka,Ireland,Lord's,145,56.0,33,6.137931,10.181818,7,0
1366,Sri Lanka,Ireland,Lord's,145,54.0,30,6.066667,10.800000,6,0
1380,Sri Lanka,Ireland,Lord's,145,39.0,16,6.115385,14.625000,5,0
1381,Sri Lanka,Ireland,Lord's,145,39.0,15,6.057143,15.600000,4,0
1395,Sri Lanka,Ireland,Lord's,145,16.0,3,6.615385,32.000000,3,0
1875,England,Australia,Bellerive Oval,156,152.0,118,12.000000,7.728814,9,1
1877,England,Australia,Bellerive Oval,156,152.0,116,6.000000,7.862069,8,1
1926,England,Australia,Bellerive Oval,156,74.0,68,9.461538,6.529412,7,1
1945,England,Australia,Bellerive Oval,156,58.0,50,8.400000,6.960000,6,1
1971,England,Australia,Bellerive Oval,156,29.0,25,8.021053,6.960000,5,1
2118,United Arab Emirates,Ireland,Al Amerat Cricket Ground Oman Cricket (Ministr...,179,178.0,115,1.200000,9.286957,9,0
2147,United Arab Emirates,Ireland,Al Amerat Cricket Ground Oman Cricket (Ministr...,179,114.0,86,11.470588,7.953488,8,0
2171,United Arab Emirates,Ireland,Al Amerat Cricket Ground Oman Cricket (Ministr...,179,90.0,63,9.368421,8.571429,7,0
2185,United Arab Emirates,Ireland,Al Amerat Cricket Ground Oman Cricket (Ministr...,179,73.0,49,8.957746,8.938776,6,0
2219,United Arab Emirates,Ireland,Al Amerat Cricket Ground Oman Cricket (Ministr...,179,31.0,16,8.538462,11.625000,5,0
2222,United Arab Emirates,Ireland,Al Amerat Cricket Ground Oman Cricket (Ministr...,179,29.0,13,8.411215,13.384615,4,0
2234,United Arab Emirates,Ireland,Al Amerat Cricket Ground Oman Cricket (Ministr...,179,15.0,3,8.410256,30.000000,3,0
2689,Bangladesh,Pakistan,Pallekele International Cricket Stadium,176,52.0,39,9.185185,8.000000,9,1
2692,Bangladesh,Pakistan,Pallekele International Cricket Stadium,176,50.0,36,9.000000,8.333333,8,1
3080,India,Sri Lanka,R Premadasa Stadium,133,121.0,104,4.500000,6.980769,9,1
3106,India,Sri Lanka,R Premadasa Stadium,133,94.0,78,5.571429,7.230769,8,1
3120,India,Sri Lanka,R Premadasa Stadium,133,78.0,65,6.000000,7.200000,7,1
3135,India,Sri Lanka,R Premadasa Stadium,133,67.0,50,5.657143,8.040000,6,1
3155,India,Sri Lanka,R Premadasa Stadium,133,39.0,30,6.266667,7.800000,5,1
3169,India,Sri Lanka,R Premadasa Stadium,133,28.0,16,6.057692,10.500000,4,1
3307,Papua New Guinea,Afghanistan,The Village,128,128.0,119,0.000000,6.453782,9,1
3368,Papua New Guinea,Afghanistan,The Village,128,71.0,60,5.700000,7.100000,8,1
3391,Papua New Guinea,Afghanistan,The Village,128,45.0,37,6.000000,7.297297,7,1
3409,Papua New Guinea,Afghanistan,The Village,128,23.0,20,6.300000,6.900000,6,1

In [319]:
#Final_doc.to_csv('T_20i.csv')

In [320]:
deliveries.to_csv('Deliveries_1.csv')

In [321]:
Final_doc.replace([np.inf, -np.inf, np.finfo(np.float64).max], np.nan, inplace=True)
Final_doc.dropna(inplace=True)

In [322]:
X = Final_doc.drop(columns = "Result")
Y = Final_doc.Result

In [323]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,Y,test_size = 0.2,random_state = 22)
#X.head(1)
#Y.head(1)
# X_train.head()
# y_train.head()

In [324]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse_output=False,drop='first'),['Batting Side','Bowling Side','Venue','Wickets Left'])
]
,remainder='passthrough')

In [325]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

In [326]:
clf = Pipeline(steps=[
    ('step1',trf),
    ('step2',LogisticRegression(solver='liblinear'))
])

In [327]:
clf.fit(X_train,y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Batting Side',
                                                   'Bowling Side', 'Venue',
                                                   'Wickets Left'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [328]:
y_pred = clf.predict(X_test)

In [329]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8662790697674418

In [330]:
from sklearn.metrics import classification_report

In [331]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.91      0.90       928
           1       0.81      0.77      0.79       448

    accuracy                           0.87      1376
   macro avg       0.85      0.84      0.85      1376
weighted avg       0.87      0.87      0.87      1376

In [355]:
def match_summary(row):
    print("Batting Team-" + row['Btting Side'] + " | Bowling Team-" + row['Bowling Side'] + " | Target- " + str(row['Target Score']))

In [360]:
deliveries['Venue'].unique()

array(['SuperSport Park', "Lord's", 'Bellerive Oval',
       'Al Amerat Cricket Ground Oman Cricket (Ministry Turf 1)',
       'Pallekele International Cricket Stadium', 'R Premadasa Stadium',
       'The Village', 'Sharjah Cricket Stadium',
       'Shere Bangla National Stadium',
       'Dubai International Cricket Stadium',
       'Civil Service Cricket Club', 'Grange Cricket Club Ground',
       'Sydney Cricket Ground', 'Hagley Oval', 'The Rose Bowl',
       'Coolidge Cricket Ground', 'ICC Academy',
       'Saurashtra Cricket Association Stadium',
       'Rajiv Gandhi International Cricket Stadium', 'Wankhede Stadium',
       'Al Amerat Cricket Ground Oman Cricket (Ministry Turf 2)',
       'Beausejour Stadium', 'Arun Jaitley Stadium', 'Kensington Oval',
       'Manuka Oval', 'OUTsurance Oval', 'Sophia Gardens',
       'Zayed Cricket Stadium', 'Adelaide Oval',
       'Vidarbha Cricket Association Stadium', 'Trent Bridge',
       'Sheikh Abu Naser Stadium', 'Newlands',
       'JSCA International Stadium Complex', 'Old Trafford',
       'Greenfield International Stadium', 'Holkar Cricket Stadium',
       'MA Chidambaram Stadium', 'Providence Stadium',
       'Mission Road Ground', 'Harare Sports Club',
       'Sheikh Zayed Stadium', 'National Stadium', 'Arnos Vale Ground',
       'New Wanderers Stadium', 'Eden Park', 'County Ground',
       'Tribhuvan University International Cricket Ground',
       'M.Chinnaswamy Stadium', 'Riverside Ground',
       'Western Australia Cricket Association Ground', 'VRA Ground',
       'Kingsmead', 'Eden Gardens', 'McLean Park',
       'National Cricket Stadium', 'Kennington Oval', 'Seddon Park',
       'Rawalpindi Cricket Stadium', 'Khan Shaheb Osman Ali Stadium',
       'GMHBA Stadium', "St George's Park", 'ICC Academy Ground No 2',
       'Mahinda Rajapaksa International Cricket Stadium', 'Warner Park',
       'Punjab Cricket Association Stadium', 'Sylhet Stadium',
       'Melbourne Cricket Ground', 'The Wanderers Stadium',
       'Maharashtra Cricket Association Stadium',
       'Rajiv Gandhi International Stadium', "Queen's Park Oval",
       'Punjab Cricket Association IS Bindra Stadium', 'Westpac Stadium',
       'Central Broward Regional Park Stadium Turf Ground',
       'M Chinnaswamy Stadium', 'Hazelaarweg', 'Castle Avenue',
       'Gaddafi Stadium', 'Wanderers Cricket Ground', 'Stadium Australia',
       'Windsor Park', 'Bready Cricket Club', 'Sportpark Westvliet',
       'Perth Stadium', 'Senwes Park', 'Gymkhana Club Ground',
       'Zahur Ahmed Chowdhury Stadium', 'ICC Global Cricket Academy',
       'Mombasa Sports Club Ground', 'Green Park',
       'Subrata Roy Sahara Stadium', 'Bay Oval', 'Boland Park',
       'Edgbaston', 'Himachal Pradesh Cricket Association Stadium',
       'Indian Association Ground', 'Narendra Modi Stadium',
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
       'R.Premadasa Stadium', 'Brisbane Cricket Ground', 'Buffalo Park',
       'Carrara Oval', 'Sawai Mansingh Stadium',
       'Greater Noida Sports Complex Ground', 'Malahide', 'Sabina Park',
       'Barabati Stadium', 'Headingley', 'P Sara Oval',
       'Tony Ireland Stadium', 'Sir Vivian Richards Stadium',
       'Goldenacre', 'Queens Sports Club',
       'Sylhet International Cricket Stadium',
       'Darren Sammy National Cricket Stadium', 'Grange Cricket Club',
       'Tolerance Oval', 'Simonds Stadium', 'Bulawayo Athletic Club',
       'Sportpark Het Schootsveld', 'Feroz Shah Kotla',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'AMI Stadium', 'Terdthai Cricket Ground', 'Moses Mabhida Stadium',
       'Mangaung Oval', 'Sardar Patel Stadium', 'John Davies Oval',
       'University Oval', 'Jade Stadium', 'White Hill Field',
       'Brian Lara Stadium', 'Clontarf Cricket Club Ground',
       'Brabourne Stadium', 'Sky Stadium', 'Maple Leaf North-West Ground',
       'Barsapara Cricket Stadium', 'Saxton Oval',
       'De Beers Diamond Oval'], dtype=object)

In [362]:
import pickle
pickle.dump(clf,open('clf.pkl','wb'))

In [365]:
deliveries['Batting Side'].unique()

array(['South Africa', 'Ireland', 'Australia', 'Pakistan', 'Sri Lanka',
       'Afghanistan', 'Zimbabwe', 'West Indies', 'Scotland',
       'Netherlands', 'New Zealand', 'England', 'United Arab Emirates',
       'Bangladesh', 'India', 'Nepal', 'Papua New Guinea', 'Hong Kong',
       'Oman', 'Namibia', 'United States of America', 'Kenya', 'Canada',
       'Austria', 'Denmark'], dtype=object)